services:
  - type: web
    name: maxx-frontend
    env: static
    rootDir: client
    buildCommand: npm install && npm run build
    staticPublishPath: build
    envVars:
      - key: NODE_VERSION
        value: 18
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    redirects:
      - source: /*
        destination: /index.html
        status: 200
